version: '3.3'

services:
  elasticsearch5:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    hostname: elasticsearch5
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - cluster.name=mia5
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    volumes:
      - ./data/elasticsearch5:/usr/share/elasticsearch/data
      - ./etc/elasticsearch5/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 19200:9200

  elasticsearch6:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.22
    hostname: elasticsearch6
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - ./data/elasticsearch6:/usr/share/elasticsearch/data
      - ./etc/elasticsearch6/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 29200:9200

  elasticsearch7:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.16.2
    hostname: elasticsearch7
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - ./data/elasticsearch7:/usr/share/elasticsearch/data
      - ./etc/elasticsearch7/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 39200:9200
